# Generated by Django 4.1.1 on 2022-09-08 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaDeSolicitacoes', '0002_mensagem_solicitacaocurso_mensagens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('autor', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitacaocurso',
            name='mensagens',
        ),
        migrations.RemoveField(
            model_name='solicitacaodisciplina',
            name='mensagens',
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
        migrations.AddField(
            model_name='mensagemdisciplina',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SistemaDeSolicitacoes.solicitacaodisciplina'),
        ),
    ]
