# Generated by Django 4.1.1 on 2022-09-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaDeSolicitacoes', '0003_mensagemdisciplina_remove_solicitacaocurso_mensagens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='ano',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023)]),
        ),
    ]
