# Generated by Django 4.1.1 on 2022-09-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaDeSolicitacoes', '0005_alter_solicitacaodisciplina_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
