# Generated by Django 4.1.1 on 2022-09-13 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaDeSolicitacoes', '0006_alter_solicitacaodisciplina_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemdisciplina',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 9, 13, 18, 8, 50, 315846, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='ano',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023)]),
        ),
    ]
