# Generated by Django 4.1.1 on 2022-09-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaDeSolicitacoes', '0008_alter_mensagemdisciplina_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoAudiovisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_responsavel', models.CharField(max_length=255, verbose_name='Professor Responsável')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=13)),
                ('data_gravacao', models.DateField(verbose_name='Data')),
                ('hora_gravacao', models.TimeField(verbose_name='Hora')),
                ('duracao', models.DurationField(verbose_name='Duração')),
                ('setor_ou_curso', models.CharField(max_length=255, verbose_name='Setor/Curso')),
                ('breve_descricao', models.TextField(verbose_name='Breve descrição')),
                ('equipamentos', models.CharField(max_length=255)),
                ('equipe', models.CharField(choices=[('S', 'Sim, precisaremos da equipe do CEAD'), ('N', 'Não, iremos utilizar a nossa própria equipe')], max_length=1)),
                ('pessoas', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
            ],
        ),
        migrations.CreateModel(
            name='MensagemCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('autor', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SistemaDeSolicitacoes.solicitacaocurso')),
            ],
        ),
    ]
