# Generated by Django 4.1.1 on 2022-09-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaDeSolicitacoes', '0009_servicoaudiovisual_mensagemcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoaudiovisual',
            name='breve_descricao',
            field=models.TextField(verbose_name='Breve descrição (no máximo 250 caracteres)'),
        ),
        migrations.AlterField(
            model_name='servicoaudiovisual',
            name='duracao',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração esperada de uso do estúdio? (campo não obrigatório)'),
        ),
        migrations.AlterField(
            model_name='servicoaudiovisual',
            name='equipamentos',
            field=models.CharField(max_length=255, verbose_name='De quais equipamentos irá precisar?'),
        ),
        migrations.AlterField(
            model_name='servicoaudiovisual',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
