# Generated by Django 4.1.1 on 2022-09-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaDeSolicitacoes', '0012_alter_solicitacaoaudiovisual_data_gravacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoaudiovisual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
