# Generated by Django 4.1.1 on 2022-10-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaDeSolicitacoes', '0014_alter_solicitacaoaudiovisual_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagemcurso',
            old_name='disciplina',
            new_name='solicitacao_curso',
        ),
        migrations.RenameField(
            model_name='mensagemdisciplina',
            old_name='disciplina',
            new_name='solicitacao_disciplina',
        ),
        migrations.AlterField(
            model_name='solicitacaoaudiovisual',
            name='duracao',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração esperada de uso do estúdio?'),
        ),
        migrations.AlterField(
            model_name='solicitacaoaudiovisual',
            name='equipe',
            field=models.CharField(choices=[('S', 'Sim, precisaremos da equipe do CEAD'), ('N', 'Não, iremos utilizar a nossa própria equipe')], max_length=1, verbose_name='Precisará dos nossos cinegrafistas ou virá com sua própria equipe de produção?'),
        ),
        migrations.AlterField(
            model_name='solicitacaoaudiovisual',
            name='pessoas',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Quantas pessoas irão participar?'),
        ),
        migrations.AlterField(
            model_name='solicitacaoaudiovisual',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocurso',
            name='curso_fim',
            field=models.DateField(verbose_name='Fim do Curso'),
        ),
        migrations.AlterField(
            model_name='solicitacaocurso',
            name='inscricoes_fim',
            field=models.DateField(verbose_name='Fim das Inscrições'),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='ano',
            field=models.IntegerField(choices=[(2021, '2021'), (2022, '2022'), (2023, '2023')]),
        ),
        migrations.AlterField(
            model_name='solicitacaodisciplina',
            name='atividades_fim',
            field=models.DateField(verbose_name='Fim das atividades'),
        ),
        migrations.CreateModel(
            name='MensagemAudiovisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('autor', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('solicitacao_audiovisual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SistemaDeSolicitacoes.solicitacaoaudiovisual')),
            ],
        ),
    ]
